### ISSUE TITLE
Multiple network connection

### ISSUE THREAD

**Issue by yamin8000** [MansourM/ez-dns-changer.bat#1]
I think there should be an option to choose which network DNS config is changed.  
I tried this tool but it changed the config of my lan configuration instead of wlan which I was using.

**Comment by yamin8000** [comment]
Oops, you already said that in the readme.

**Comment by MansourM** [comment]
Hey @yamin8000 ,
thanks for reaching out.
I knew there could be a problem but since I was not sure how to reproduce it, just left it there 😄  
can you please make a `name.bat` file with this code, run it and report the result?
````
@echo off

netsh interface show interface

echo.
echo =-=-=-=-=-=-=-=-=-=-=
echo.

wmic nic where "NetConnectionStatus=2" get NetConnectionID |more +1

echo.
echo =-=-=-=-=-=-=-=-=-=-=
echo.

setlocal enabledelayedexpansion

set /a x = 0
FOR /F "tokens=*" %%G IN ('wmic nic where "NetConnectionStatus=2" get NetConnectionID ^|more +1') DO (
set Connections[!x!]=%%G
set /a x+=1
)

set /a x-=2

FOR /L %%i IN (0 1 %x%) DO (
set /a index=%%i+1
call echo     !index!. %%Connections[%%i]%%
)

pause
````

**Comment by yamin8000** [comment]
> Hey @yamin8000 , thanks for reaching out. I knew there could be a problem but since I was not sure how to reproduce it, just left it there 😄 can you please make a `name.bat` file with this code, run it and report the result?
> 
> ```
> @echo off
> 
> netsh interface show interface
> 
> echo.
> echo =-=-=-=-=-=-=-=-=-=-=
> echo.
> 
> wmic nic where "NetConnectionStatus=2" get NetConnectionID |more +1
> 
> echo.
> echo =-=-=-=-=-=-=-=-=-=-=
> echo.
> 
> setlocal enabledelayedexpansion
> 
> set /a x = 0
> FOR /F "tokens=*" %%G IN ('wmic nic where "NetConnectionStatus=2" get NetConnectionID ^|more +1') DO (
> set Connections[!x!]=%%G
> set /a x+=1
> )
> 
> set /a x-=2
> 
> FOR /L %%i IN (0 1 %x%) DO (
> set /a index=%%i+1
> call echo     !index!. %%Connections[%%i]%%
> )
> 
> pause
> ```

![image](https://user-images.githubusercontent.com/5001708/228536054-3e9f96d6-98bf-422b-8e63-4aad33616a52.png)

**Comment by yamin8000** [comment]
Windows 10/11 fancy terminal/PowerShell

![image](https://user-images.githubusercontent.com/5001708/228536354-0482a3c8-0bea-4153-a451-f81a87e90ac3.png)
